version: '3'
services:
  backend:
    image: backend-image
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/runGroop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 15881577.p
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  database:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: runGroop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 15881577.p
