apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: my-namespace
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/runGroop"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

